PackageIdentifier: xidl.xidlc
PackageVersion: 0.58.0
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: xidlc.exe
        PortableCommandAlias: xidlc
    Commands:
      - xidlc
    InstallerUrl: https://github.com/xidl/xidl/releases/download/v0.58.0/xidlc-x86_64-pc-windows-msvc.zip
    InstallerSha256: 0D698B5C4D1B1F48A72FF0CBAD6E3139A60356D1DF7D6A53A34CA79F8810366B
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: xidlc.exe
        PortableCommandAlias: xidlc
    Commands:
      - xidlc
    InstallerUrl: https://github.com/xidl/xidl/releases/download/v0.58.0/xidlc-aarch64-pc-windows-msvc.zip
    InstallerSha256: FB98D2B9C59EEF28D7156B9CF641DF94D398BA13E1C6279CE3C98BC35C766F3C
ManifestType: installer
ManifestVersion: 1.12.0
