PackageIdentifier: xidl.xidlc
PackageVersion: 0.78.0
Installers:
  - Architecture: x64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: xidlc.exe
        PortableCommandAlias: xidlc
    Commands:
      - xidlc
    InstallerUrl: https://github.com/xidl/xidl/releases/download/v0.78.0/xidlc-x86_64-pc-windows-msvc.zip
    InstallerSha256: E1052967F7B779180986BBCB765BB357DCA766B5E24BAA8900BC6FBFC2A5522E
  - Architecture: arm64
    InstallerType: zip
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: xidlc.exe
        PortableCommandAlias: xidlc
    Commands:
      - xidlc
    InstallerUrl: https://github.com/xidl/xidl/releases/download/v0.78.0/xidlc-aarch64-pc-windows-msvc.zip
    InstallerSha256: 8262E2F15B5791F2205A7B7A66222FDEF04751E96E9B14B46402CBE499110D38
ManifestType: installer
ManifestVersion: 1.12.0
